language: python
python:
  - "3.6"
# command to install dependencies
env:
 - FLASK_VERSION=1.0.2 
 
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install codeclimate-test-reporter
# command to run tests

before_script:
  - psql -c "CREATE DATABASE test_questioner;" -U postgres
  - coveralls

script:
  - python3 -m pytest --cov=app --cov-report term-missing

after_success:
  - coveralls
  - coverage xml
  - codeclimate-test-reporter
  
