language: python
python:
  - "3.6"
# command to install dependencies
env:
 - FLASK_VERSION=1.0.2 
 
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install codeclimate-test-reporter
  - pip install pytest-cov
# command to run tests

services: 
  - postgresql

before_script:
  - psql -c "CREATE DATABASE questioner_test;"
  - coveralls

script:
  - py.test --cov
  - export FLASK_ENV='testing'
  - export JWT_SECRET_KEY = 'b'gn%\x92\x08Zp\xffZgg~\xa4\xfcY\x8b\xb4H\xebL\xd7\xa4\x80V'
  - export TEST_DATABASE_URL='postgres://localhost:5432/questioner_test'
#   -m pytest --cov=app --cov-report term-missing

after_success:
  - coveralls
  # - coverage xml
  # - codeclimate-test-reporter
  
cache:
  - pip
